[package]
name = "next-transform-cjs-finder"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"

[lib]
bench = false

[dependencies]
turbopack-binding = { workspace = true, features = [
  "__swc_core",
] }

